import { render } from '@testing-library/react';
import RootLayout, { metadata } from './layout';

jest.mock('next/font/local', () => () => ({
  variable: 'mock-font-variable',
}));

describe('RootLayout', () => {
  it('renders children inside body', () => {
    const { container } = render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    // Query for the text within the rendered container
    expect(container).toHaveTextContent('Test Child');
  });

  it('sets html lang attribute to en', () => {
    render(
      <RootLayout>
        <div />
      </RootLayout>
    );
    expect(document.documentElement).toHaveAttribute('lang', 'en');
  });
});

describe('metadata', () => {
  it('has correct title and description', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });
});
